import Provider from './Provider';
import Header from './Header';
import Main from './Main';
import Footer from './Footer';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: {
		default: '記事投稿アプリ',
		template: '%s | 記事投稿アプリ',
	},
	description: 'Generated by create next app',
	// TODO: favicon not working
	// icons: {
	// 	icon: 'favicon.ico',
	// },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="ja">
			{/* <head /> */}
			<body>
				<Provider>
					<Header />
					<Main>{children}</Main>
					<Footer />
				</Provider>
			</body>
		</html>
	);
}
