import './globals.css';
import Provider from './Provider';
import Header from './Header';
import Main from './Main';
import Footer from './Footer';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	// TODO: favicon not working
	icons: {
		icon: { url: '/favicon.ico', type: 'image/png' },
	},
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="ja">
			<head />
			<body>
				<Provider>
					<Header />
					<Main>{children}</Main>
					<Footer />
				</Provider>
			</body>
		</html>
	);
}
